### PR TITLE
feat: compress readme screenshot image

### LINKED ISSUE #214: Replace PNG images in README with WebP
These are the screenshots in README which are in PNG format

```
<div style="display:flex; flex-wrap: wrap;">
  <img src="https://github.com/SankethBK/diaryvault/assets/51091231/3030fcb2-18eb-4fd9-abb5-bb8343524495" style = "padding: 1rem; height: 300px">
  <img src="https://github.com/SankethBK/diaryvault/assets/51091231/d8d8cb28-6eef-4b99-83e9-096d32fa7233" style = "padding: 1rem; height: 300px">
  <img src="https://github.com/SankethBK/diaryvault/assets/51091231/27f90610-9d20-42a3-bc44-09abd5e9d538" style = "padding: 1rem; height: 300px">
  <img src="https://github.com/SankethBK/diaryvault/assets/51091231/b9816cfc-d0f7-4319-b1d2-c737afb7d8d0" style = "padding: 1rem; height: 300px">
  <img src="https://github.com/SankethBK/diaryvault/assets/51091231/5eed68a2-ae46-4c7b-8e10-f2080057cb8d" style = "padding: 1rem; height: 300px">
  <img src="https://github.com/SankethBK/diaryvault/assets/51091231/9f811ef8-35b5-4212-b8a9-5c96444ce4a4" style = "padding: 1rem; height: 300px">
  <img src="https://github.com/SankethBK/diaryvault/assets/51091231/209849ac-e5bc-4b5d-ac5f-c6f4afd72dcb" style = "padding: 1rem; height: 300px">
  <img src="https://github.com/SankethBK/diaryvault/assets/51091231/adb2ee90-8097-40ba-9f37-eee7d4a708fc" style = "padding: 1rem; height: 300px">
</div>
```

They take long time to render, so we need to convert them to WebP to reduce image size, thus render time. You can open these Urls, download the images, convert them to webp and paste the updated images. 

You can use https://cloudconvert.com/png-to-webp for conversion.

### PR DESCRIPTION
**Pull request by devpawann**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [x] Optimization
- [ ] Documentation Update

## Description
Update the Readme image with a compressed image to load faster.

## Featured Covered in this PR

- [x] Update readme images

## Related Tickets & Documents

- Related Issue #214
- Closes #214

## Screenshots, Recordings

*Please replace this line with instructions on how to test your changes, or any screenshots or recording you can attach here.*

## Tested Feature??

- [ ] In Real Device.
- [ ] In Emulator
- [x] Web

### CODE REVIEW

**Comment by devpawann** [comment]
https://github.com/orgs/community/discussions/5470

Since GitHub doesn't support WEBP, I compressed image up to 75% on average without losing quality.

**Comment by SankethBK** [comment]
Hi, I think github doesn't allow to upload webp via browser. But we can include it as normal file in codebase and use hyperlink to display it in README. Can you create a folder readme-assets in the repo and link place the images inside it.

**Comment by devpawann** [comment]
@SankethBK 
I included the assets on the repo, You can have a look,

**Comment by SankethBK** [comment]
Thanks for contributing!

**Review by SankethBK — APPROVED** [review]

**Pull request merged**
