### PR TITLE
Feature/Hebrew translation

### PR DESCRIPTION
**Pull request by TomerPacific**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [X] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
Added Hebrew translation

## Featured Covered in this PR

- [X] Creating app_he.arb file and adding translations there
- [X] Adding Locale in app.dart

## Related Tickets & Documents

- Related Issue #75 

## Screenshots, Recordings
qemu-system-x86_64_5UrKlZhNDu

qemu-system-x86_64_j2zDsoNUyr

## Tested Feature??

- [ ] In Real Device.
- [X] In Emulator

### CODE REVIEW

**Review by SankethBK — APPROVED** [review]
LGTM, can you check the linter error. I think its because this line exceeds 80 characters
```
          supportedLocales: const [Locale('en'), Locale('hi'), Locale('pa'), Locale('he')],
```

**Comment by TomerPacific** [comment]
Sure @SankethBK . Would you like me to just break that line into two?

**Comment by SankethBK** [comment]
> Sure @SankethBK . Would you like me to just break that line into two?

@TomerPacific you can add a trailing comma after `Locale('he')`, it will break the array into multiple lines

**Comment by SankethBK** [comment]
@TomerPacific it would be like this after formatting
```
          supportedLocales: const [
            Locale('en'),
            Locale('hi'),
            Locale('pa'),
            Locale('he'),
          ],
 ```

**Pull request merged**
