### PR TITLE
declutter settings page

### LINKED ISSUE #218: Declutter Settings Page
The current Settings page displays all options on a single screen. Even though similar options are grouped and expandable on click, the page has become cluttered and overwhelming for users.

**Proposed Solution:**

Redesign the Settings page to display only the primary categories:

- **Cloud Backup**
- **Security**
- **Reminders**
- **Customize Theme, Fonts, and Language**

(Keep rest of the options like Send Feedback, Share with Friends, Project on Github and App version as it is)

On clicking these options, further relevant options needs to be displayed on a different screen.

Widgets Involved:
```
- lib/core/pages/settings_page.dart
- lib/core/widgets/settings_tile.dart
```

Tasks

- [ ] Create a new page `settings_details.dart` in ` lib/core/pages`.
- [ ] Remove widgets from `ListView` in `settings_page.dart` and addthe following options. (Use `SettingsTile` widget to display these options.)
    - Cloud Backup 
    - Security
    - Reminders
    - Customize Theme,  Fonts and Language
- [ ] On clicking any of the primary categories, navigate to `settings_details.dart`. Pass route parameters (e.g., **pageTitle**) to identify which category's settings to display in `settings_details.dart`.

### PR DESCRIPTION
**Pull request by devpawann**
## What type of PR is this? (check all applicable)

- [x] Refactor
- [ ] Feature
- [ ] Bug Fix
- [x] Optimization
- [ ] Documentation Update

## Description
Move some settings options from SettingsPage to SettingsDetailPage.

## Related Tickets & Documents
- Related Issue #218
- Closes #218 

## Tested Feature??

- [x] In Real Device.
- [ ] In Emulator

### CODE REVIEW

**Comment by SankethBK** [comment]
Hi, this is correct, just small suggestions:

1. Keep `SetupAccount` widget in `SettingsDetailPage` itself at the top.
2. Move the "AutoSaveToggleButton" from Reminders to cloud backup.
3. Remove Daily Reminders expandable tile and show the options directly just like you did for Security Settings.

**Comment by devpawann** [comment]
1. Do you mean place `SetupAccount` in the outer page 'SettingsPage`?
2. Done
3. Done
4. Export notes done - I didn't see Import note implementation though
@SankethBK

**Comment by SankethBK** [comment]
> Do you mean place SetupAccount in the outer page SettingsPage ?

yes

> Export notes done - I didn't see Import note implementation though

Its not there yet, planning to add it.

**Comment by devpawann** [comment]
@SankethBK 
You can now review

**Review by SankethBK — APPROVED** [review]
Thanks for contributing! I added some minor changes related to padding.

**Pull request merged**
