### PR TITLE
added page View, need help with states in PageView Builder

### PR DESCRIPTION
**Pull request by zdoryyk**
## What type of PR is this? (check all applicable)

- [ ] #217 

## Description
 Added almost all features from issue
## Featured Covered in this PR

- [x] Modify NotePreviewCard to accept an index parameter from home screen's Listview.
- [x] Modify NotesReadOnlyPage to accept indexas route parameter and pass index from NotePreviewCard which will serve as initial index for swipe navigation.
- [x] Implement a PageView in NotesReadOnlyPage that allows swiping between notes in read-only mode.
- [ ] Ensure that the notes load correctly when swiped left or right.

## Related Tickets & Documents
- [ ] #217 
- [ ] #217  

## Screenshots, Recordings

https://github.com/user-attachments/assets/ec005646-646f-4d86-b08b-3b8adc21e5f3

## Tested Feature??

- [ ] In Real Device.
- [x] In Emulator

### CODE REVIEW

**Comment by zdoryyk** [comment]
I should fix that state, But I have no idea how to, can someone help me?

**Comment by SankethBK** [comment]
Hi, the issue is because you are adding `notesBloc.add(InitializeNote(id: noteId);` inside `itemBuilder`, when this happens a new note is fetched and the new note is sent to all the BlocBuilders listening to `notesBloc`. So as a result both current and next/previous pages are getting updated with same note. 

I have added fix in this commit [290b2d090ad4a7a74d031ba027be70a926aa61b3](https://github.com/SankethBK/diaryvault/commit/290b2d090ad4a7a74d031ba027be70a926aa61b3), just cherry-pick this commit to your PR.

As a fix i have added `buildWhen` to rebuild only if the id matches the id of the note we got from index. This ensures we rebuild only for 1 page.
```
               buildWhen: (previousState, currentState) {
                    
                          if (currentState.safe) {
                            // Rebuild only if the note in the bloc matches the note ID of this page
                            return currentState.id == _notePreview.id;
                          }
                          return false; 
                        },
 ```
 
 I also made some more changes
 
 1. Instead of passing noteIds as route parameter, i am fetching it using `BlocProvider.of<NotesFetchCubit>(context);`.
 2. Instead of passing `index` in route parameter, i am iterating through the array of notes and checking which id matches the id we got from route param, the advantage of this is we are no longer dependant on id from route param and the solution can also be extended to the case when we open `NotesReadOnlyPage` from `NoteCreatePage`. 
 
 Currently there is another small bug: When we open `NotesReadOnlyPage` from `NoteCreatePage` by clicking on eye button we are not passing note id as a result it assumes id as 0 and goes to first note. We can pass id here also from route param so that it works correctly for this case as well.

**Comment by zdoryyk** [comment]
ty very much for your response, I got it

**Comment by zdoryyk** [comment]
Also I have had problem with Tags, the same problem as we had before, I have added _notePreview.id to NoteTags params, now id does work correct

**Comment by zdoryyk** [comment]
@SankethBK Hi again, we have also problem with TAGS, When i trying to add, I have null error operator, how can I fix it?

**Comment by SankethBK** [comment]
Hi, can you share a screen recording of the issue

**Comment by zdoryyk** [comment]
> Hi, can you share a screen recording of the issue

Look tags

https://github.com/user-attachments/assets/1af40f80-0f03-46ad-9781-c1e5c5ac22b8

**Comment by zdoryyk** [comment]
https://github.com/user-attachments/assets/373fdb6f-502b-462f-9c59-a6b62a3854c4

also this bug, when i trying to add bug

**Comment by SankethBK** [comment]
Hey, i tried couple of things, i was able to solve the tags issue but ran into some null value issue somewhere. I will try again and update you by tomorrow

**Review by SankethBK — APPROVED** [review]
I'll merge it to master once i fix these issues

**Comment by SankethBK** [comment]
Hey i have added fixes in this [PR](https://github.com/SankethBK/diaryvault/pull/238/files)
Mainly i had to fix these issues
1. Don't allow swipe navigation if note read page is opened from note create page as the note could've been edited. For this i wam checking if `id` is null, means the navigation happened from note create page instead of home page in such cases don't render pageview at all. 
2. Tags issue is happening its being fetched from `BlocBuilder`, since `notesBloc` holds the state of currently active note, tags of that note will be updated. Fix was to pass tags from `NoteReadOnlyPage` rather than reading from `BlocBuilder`.

**Comment by zdoryyk** [comment]
Hello, thanks, I will change it

**Comment by SankethBK** [comment]
I already added the changes, just letting you know

**Pull request merged**
