### PR TITLE
changed splash screen image which is having a typo, "closes #107" would connect the current pull request to issue 107

### LINKED ISSUE #107: Typo in splash screen image
The image `assets/images/splash_screen.png` has a typo in the app name. It says "Dairy Vault" instead of "Diary Vault"

splash_screen

### PR DESCRIPTION
**Pull request by Srujithchaithanya1**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [] Optimization
- [ ] Documentation Update

## Featured Covered in this PR

- [x] Task 1
- [x] Task 2

## Related Tickets & Documents

- Related Issue #
- Closes #

## Screenshots, Recordings

*Please replace this line with instructions on how to test your changes, or any screenshots or recording you can attach here.*

## Tested Feature??

- [ ] In Real Device.
- [x] In Emulator

### CODE REVIEW

**Review by ayato91 — CHANGES_REQUESTED** [review]
@Srujithchaithanya1 
1. Previous image may required for App Logo
2. Still There is a typo in Daily spelling (in Right Page)

**Comment by SankethBK** [comment]
Art is good, but its not recommended to use full screen images for splash screen

**Comment by SankethBK** [comment]
Hi @ayato91 , actually we need the image for different screen sizes. There are different drawable folders inside `android/app/src/main/res`. We can generate these drawables for different screen sizes in Android studio, but if we use png it would reduce the quality in lower dpi screens. I previously used this SVG file to generate them, see if you can edit this SVG itself to fix the typo
logo

**Comment by SankethBK** [comment]
Closing, as there is another PR for same

**Pull request closed without merging**
