### PR TITLE
#67 Fixed syntax errors

### LINKED ISSUE #67: Need help with fixing syntax errors!!
Need help with fixing these syntax errors like these...
 
Screenshot 2023-10-07 at 05 49 52

Steps to recreate:
1.  make sure to have [this](https://github.com/SankethBK/diaryvault/pull/66/files#diff-a58d5995c53d2528e852d3b32cfd236c6c0e8498880065242df4e879273de061) file in your root directory
2. In your terminal run: ` bash pre-commit`

_Originally posted by @micedreams in https://github.com/SankethBK/diaryvault/issues/66#issuecomment-1751521221_

### PR DESCRIPTION
**Pull request by bibekpanda55**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Optimization

## Featured Covered in this PR

-Fixed syntax errors across files after running `bash pre-commit`

## Related Tickets & Documents

- Related Issue #67 
- Closes #67 

## Screenshots, Recordings

Have attached screenshot after  resolving all the syntax errors and then running the command `bash pre-commit`.

## Tested Feature??
Screenshot 2023-10-09 at 8 19 54 PM

### CODE REVIEW

**Comment by bibekpanda55** [comment]
@micedreams @SankethBK Please check this PR and merge it if you don't find any issues. That would help. Thanks

**Comment by SankethBK** [comment]
@bibekpanda55 let's avoid making changes inside `packages` as it could create bugs and makes it difficult to update packages.

We can add this in `analysis_options.yaml` to ignore linting for `packages` folder [ref](https://stackoverflow.com/questions/61225223/exclude-all-generated-code-from-dartanalyzer)


```
analyzer:
  exclude:
    - packages/**
```

**Comment by SankethBK** [comment]
Sure, @bibekpanda55 , thanks for the contribution. Merging this to a temporary branch as we need some changes in `analysis_options.yaml`. I'll create new issue for this

**Review by SankethBK — APPROVED** [review]

**Comment by bibekpanda55** [comment]
I could have added that line `analysis_options.yaml` file that was not an issue. I thought you were asking to revert back the changes made in all files under packages folder.

**Comment by SankethBK** [comment]
yes, we need to revert the changes in the packages folder as well, as commenting code in package might break some functionality. It's fine as we didn't mention this in the issue earlier

**Comment by bibekpanda55** [comment]
Got it. Still have created a PR after changing the analysis_options.yaml file as you said in the fix_linter_errors branch

**Comment by SankethBK** [comment]
Thank you, merged it

**Pull request merged**
