### PR TITLE
#Hacktoberfest 2023

### LINKED ISSUE #13: Add new themes
Refer the documentation of [themes](https://github.com/SankethBK/diaryvault/blob/master/docs.md#theming). 

To add a new theme
* Decide if it's a dark theme or a light theme.
* Prepare a background image and a color palette that matches / compliments colors in the background image. 
* If it's light theme, most of the colors from `lib/app/themes/coral_bubble_theme.dart` can be reused. If its a dark theme, most of the colors from `lib/app/themes/cosmic_theme.dart` can be re-used 

Start by altering the background image and colors of any existing theme, when its finalized create a new class in `lib/app/themes/theme_extensions`. 

Reference PR for adding a new theme: https://github.com/SankethBK/diaryvault/pull/36

### PR DESCRIPTION
**Pull request by Redvey**
## Description
This pull request introduces a Dark Academia theme for Diary Vault, enhancing the visual aesthetics of the app. The Dark Academia theme creates a vintage and scholarly appearance, aligning with the desired style for the app. This theme will offer users a unique and visually pleasing experience.

## Featured Tasks
- [x] Defined the Dark Academia color scheme: The color scheme has been carefully chosen to reflect the Dark Academia style, with a focus on muted and earthy tones.
- [x] Implemented Dark Academia styling for various UI elements: UI elements such as buttons, text fields, app bars, and note previews have been restyled to fit the Dark Academia theme.
- [x] Verified theme consistency across all screens: We have performed initial testing to ensure that the Dark Academia theme is applied consistently throughout the app.

## Related Tickets & Documents 
- Closes #13: This PR addresses the issue related to implementing the Dark Academia theme.
- I followed the design guidelines to ensure the theme aligned with the overall app design.

## Screenshots

https://github.com/SankethBK/diaryvault/assets/128305006/1364c24e-8922-472d-9871-c77f79917013

Screenshot 1
Screenshot 2
Screenshot 3
Screenshot 4

## Tested Feature
- [x] Tested on a physical Android device (Pixel 4): We ensured that the Dark Academia theme works on real Android devices.
- [x] Tested on an iOS simulator (iPhone 11 Pro): The theme was tested on an iOS simulator to guarantee a consistent experience across platforms. 

The Dark Academia theme not only adds a touch of elegance to the Diary Vault app but also provides users with a visually engaging and cohesive experience that aligns with the Dark Academia style.

### CODE REVIEW

**Comment by SankethBK** [comment]
This looks cool! I'll review it by today

**Comment by Redvey** [comment]
> This looks cool! I'll review it by today

Thank you so means, it means a lot.

**Comment by Redvey** [comment]
@SankethBK Hello there, any update regarding reviews?

**Comment by SankethBK** [comment]
Hi @Redvey , I reviewed the PR. It looks good, but needs small corrections at some places. I will fix them, thanks for the contribution

**Comment by Redvey** [comment]
Hello! Thank you for taking the time to review the PR. I'm pleased to know it appears satisfactory in general. I'd greatly appreciate any specific pointers on areas that require improvement. Your guidance is invaluable, and I'm genuinely thankful for the chance to contribute.

**Comment by SankethBK** [comment]
It needs only minor corrections like icons in login page isn't visible and transparency needs to be fine tuned at some places. But my major concern is that the background image is from Pinterest, so we cannot use it directly. We can use AI generated images with similar color theme and setting.

**Comment by Redvey** [comment]
Thank you for informing me, I will definitely better it.

**Pull request merged**
