### PR TITLE
Added theme lush-green

### PR DESCRIPTION
**Pull request by KMayank02**

### CODE REVIEW

**Comment by SankethBK** [comment]
Hey, this looks amazing! Thanks for the contribution

**Review by SankethBK — APPROVED** [review]
Remove the changes from pubspec.lock as we are not adding / updating any packages in this PR. Rest all looks good!

**Comment by KMayank02** [comment]
Can you check if its fixed?

**Comment by SankethBK** [comment]
Looks good, I'll merge this if you don't have any pending changes

**Comment by KMayank02** [comment]
Yes its done. Thank you

**Pull request merged**
