### PR TITLE
Add Font size and family customization

### PR DESCRIPTION
**Pull request by nandhagobal**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Featured Covered in this PR

- [ ] Task 1
- [ ] Task 2

## Related Tickets & Documents

- Related Issue #
- Closes #

## Screenshots, Recordings

*Please replace this line with instructions on how to test your changes, or any screenshots or recording you can attach here.*

## Tested Feature??

- [ ] In Real Device.
- [ ] In Emulator

### CODE REVIEW

**Comment by nandhagobal** [comment]
hi @SankethBK can you please review this code

**Comment by SankethBK** [comment]
I'll review by today

**Comment by SankethBK** [comment]
Hi @nandhagobal , this is pretty nice, same as what I was planning.

**Comment by SankethBK** [comment]
Merging this to `font_customization` branch. I need to check if its possible to extend font size customization to rich text editor also.

**Pull request merged**
