### PR TITLE
Updated the file by adding pause button functionality and created read_notes.dart in widgets directory.

### PR DESCRIPTION
**Pull request by Night-Amber3301**
solves: #60 

Updated the file by adding pause button functionality and created read_notes.dart in widgets directory

### CODE REVIEW

**Comment by SankethBK** [comment]
I'm sorry that's not what I meant by creating a new widget for the `IconButton`. There are multiple syntax errors. Feel free to pick easier issues if you need to ramp up with Flutter syntax

**Comment by Night-Amber3301** [comment]
Yeah sure, actually I'm new to open-source and learned a lot from your project, thanks for your time and consideration.
Will continue my journey with more beginner-friendly issues.

**Comment by SankethBK** [comment]
No worries, your code is pretty close to a working solution. It's just that you need to encapsulate this widget into a new stateful widget which will hold the state variable `isPlaying`. 

```
 IconButton(
              icon: isPlaying ? Icon(Icons.pause) : Icon(Icons.play_arrow),
              onPressed: () {
              if (isPlaying) {
                _pause();
              }     
              else  
              {
                _speak(notesBloc.state.title! + ". " + notesBloc.state.controller!.document.toPlainText());
              }
              setState(() {
                isPlaying = !isPlaying;
                });
              },
            )
 ```

**Comment by SankethBK** [comment]
I will refactor your code. I have changed the target branch. You can check this [issue](https://github.com/SankethBK/diaryvault/issues/59) for a simpler one

**Comment by Night-Amber3301** [comment]
Thank you sir.

**Pull request merged**
